//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shkola17.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class broken_device
    {
        public int ID_invent { get; set; }
        public string vid_tehnika { get; set; }
        public string Comment { get; set; }
        public string date_broken { get; set; }
    
        public virtual Invent Invent { get; set; }
    }
}
