//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shkola17.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invent
    {
        public int ID_invent { get; set; }
        public Nullable<int> floor { get; set; }
        public string cabinet { get; set; }
        public string Tehnika { get; set; }
        public string internal_devices { get; set; }
        public string FIO_upravl { get; set; }
        public Nullable<System.DateTime> date_buy { get; set; }
        public byte[] photo { get; set; }
    
        public virtual broken_device broken_device { get; set; }
    }
}
