//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shkola17.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class model
    {
        public int Id_inv { get; set; }
        public string device { get; set; }
        public string printer { get; set; }
        public string scanner { get; set; }
        public string proektop { get; set; }
    
        public virtual Invent Invent { get; set; }
    }
}
