//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shkola17.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class invent_tehnikaEntities : DbContext
    {
        private static invent_tehnikaEntities _context;
        public invent_tehnikaEntities()
            : base("name=invent_tehnikaEntities")
        {
        }
        public static invent_tehnikaEntities GetContext()
        {
            if (_context == null)
                _context = new invent_tehnikaEntities();
            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<broken_device> broken_device { get; set; }
        public virtual DbSet<Invent> Invent { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<user> user { get; set; }
        public virtual DbSet<Images> Images { get; set; }
    }
}
